import = [
    "~/.config/alacritty/themes/themes/dark_pastels.toml"
]

[font]
size = 12.0
offset.x = 1  # For letter spacing (default: 0)
offset.y = 2  # For line spacing (default: 0)

[font.bold]
family = "Agave Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Agave Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Agave Nerd Font"
style = "Italic"

[font.normal]
family = "Agave Nerd Font"
style = "Regular"

